### ISSUE TITLE
baseline 4.0 offset

### ISSUE THREAD

**Issue by bmarengo** [cirrus-geo/cirrus-earth-search#26] opened 2022-03-10 12:46 UTC
Hi! I've just noticed that now the baseline4.0 offset is being applied to cogs images. This was not happening a few weeks ago. Can you please let me know since when images are being corrected? What happens with values lower than 1000? Do all images since 2022/1/25 have the offset applied?

I maintain a big service that consumes these images and need to know ASAP!

Thank you in advance.

**Comment by fschlenz** [comment] 2022-06-27 10:14
Dear @matthewhanson, thanks for your information on this issue! 

Could you please update us on the status of your reprocessing campaign? When do you expect it to be finished?

We have used some of the old baseline 4.00 images without the flag sentinel:boa_offset_applied and applied the flag ourselves. Now we would like to know when you have updated all of them. 

Many thanks in advance for the support.

**Comment by matthewhanson** [comment] 2022-07-22 15:24
@fschlenz Sorry for the delay. We have applied the offset to all scenes that fall within Africa, and some portion of the scenes outside of there. I don't have an estimate of when it will be done as this work has been delayed due to a few reasons. 

I'll update this thread when we have more information.

**Comment by ungarj** [comment] 2022-11-07 12:44
Hi @matthewhanson! What did you do in case you encountered negative values? Did you change the COG dtype to int16 or clipped the values to the uint16 range (i.e. set all negative values to 1)?

**Comment by ungarj** [comment] 2022-11-07 12:58
To provide an example: [this product](https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_32TMS_20220225_0_L2A) is from processing baseline 04.00 but is missing `sentinel:boa_offset_applied`, so I would assume there is an offset to be substracted from the image values.

However, [B02](https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/32/T/MS/2022/2/S2B_32TMS_20220225_0_L2A/B02.tif) has patches of values below 1000 which would result in negative values after substracting the offset.

**Comment by piyushrpt** [comment] 2022-12-28 20:13
Any updates on this thread? Is there a known mechanism to determine when these changes are made. For example, are these update messages also published to the SNS topic?

**Comment by piyushrpt** [comment] 2023-01-02 03:00
Our quick analysis shows that there are about 274K images (~7.5%) that still need to be updated / or their metadata needs to be updated.

**Comment by piyushrpt** [comment] 2023-01-05 22:07
Would this be the best/ most effective way to identify STAC items that have been updated in the last 24 hours:

```
    URL = "https://earth-search.aws.element84.com/v0"
    tnow = datetime.datetime.utcnow()
    tbef = tnow - datetime.timedelta(days=1)

    # Query STAC endpoint
    query = satsearch.Search.search(
        url=URL,
        collections=["sentinel-s2-l2a-cogs"],
        query={
            "updated": {
                "lt": tnow.isoformat(),
                "gt": tbef.isoformat(),
            }
        }
    )
    print(query.found())
    items = query.items()
```

Would the `updated` time tag in metadata be modified if anything associated with the assets change? I'm trying to identify a mechanism for tracking changes that may result in update of STAC metadata or assets.

**Comment by gadomski** [comment] 2023-08-14 22:28
Closing this as a duplicate of https://github.com/Element84/earth-search/issues/9

**Closed** 2023-08-14 22:28 UTC
Labels: duplicate
