### ISSUE TITLE
Partial granule_metadata files

### ISSUE THREAD

**Issue by piyushrpt** [cirrus-geo/cirrus-earth-search#39] opened 2023-05-16 22:48 UTC
Looks like some of the granule_metadata XML files for the S2 L2A collection are truncated.

One example:

`S2B_23WPR_20230515_0_L2A`

**Comment by ircwaves** [comment] 2023-05-17 10:57
Thanks for the report @piyushrpt.  

Some notes:

https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/23/W/PR/2023/5/S2B_23WPR_20230515_0_L2A/granule_metadata.xml

```xml
  ... snipped ...

        <Azimuth>
          <COL_STEP unit="m">5000</COL_STEP>
          <ROW_STEP unit="m">5000</ROW_STEP>
          <Values_List>
            <VALUES>185.235 185.385 185.535 185.685 185.835 185.985 186.135 186.284 186.434 186.584 186.734 186.884 187.033 187.183 187.333 187.482 187.632 187.781 187.931 188.08 188.229 188.379 188.528</VALUES>
            <VALUES>185.236 185.386 185.535 185.685 185.8
```

Stops at a size of 7633 characters.

Not broken on scihub: S2B_OPER_MSI_L2A_TL_2BPS_20230515T172551_A032326_T23WPR_N05.09

**Comment by gadomski** [comment] 2023-08-14 22:22
Closing this as a duplicate of https://github.com/Element84/earth-search/issues/6.

**Closed by gadomski** 2023-08-14 22:22 UTC
