### ISSUE TITLE
Missing scenes

### ISSUE THREAD

**Issue by JonDHo** [cirrus-geo/cirrus-earth-search#41] opened 2023-07-03 15:38 UTC
Hi,
there are quite a few scenes which appear on Open Hub from approximately a week ago, but are not in the S3 bucket nor in the v1 STAC Catalog. As an example, this query returns no results: [https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2023-06-27T00:00:00Z/2023-06-28T00:00:00Z&bbox=-72.5,-35,-72,-34.5](https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2023-06-27T00:00:00Z/2023-06-28T00:00:00Z&bbox=-72.5,-35,-72,-34.5)

but on Open Hub, the same area and dates result in multiple scenes, showing the recent major floods in Chile
![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/83f19bf3-f154-446f-a958-793da0765f3d)
![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/5ff3996e-ac5f-4ee1-9409-46976a20642a)

The scenes that should exist in this query include for:
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HBB_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYG_20230627T224707
- S2A_MSIL1C_20230627T143731_N0509_R096_T19HBB_20230627T210535
- S2A_MSIL1C_20230627T143731_N0509_R096_T18HYG_20230627T210535

All appear to have passed quality checks.

**Comment by alvaroparedesl** [comment] 2023-07-03 16:14
Hi,

I'm having the same problem and it would be nice to have these images as we had a big flood during these days.

Regards

**Comment by JavierLopatin** [comment] 2023-07-03 16:16
Same here! Thanks for your help.

Cheers, J

**Comment by JonDHo** [comment] 2023-07-03 17:03
It seems that lots of people are looking for this data and have found the same issue because of the floods here in Chile are creating a lot of interest. I have also found several other people who have independently come across the same problem. We are consuming this into an Open Data Cube platform. The image below shows the scenes the gaps in the data from across Chile.

<img width="380" alt="image" src="https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/716779a0-59b4-4b68-b7e6-3d32029daf20">

**Comment by piyushrpt** [comment] 2023-07-03 17:34
I suspect these are still in the processing queue as ESA has started its largest historical reprocessing campaign at the rate of about 200K L2A images per day.

**Comment by JonDHo** [comment] 2023-07-03 17:39
ok... it is a bit annoying as the following days have good coverage but this one critical day is patchy. The image below is the coverage for yesterday (from the S3 bucket), but the image above is from 6 days ago and the gaps haven't changed.
![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/0294a1d1-1295-4e27-9386-3d94509e9379)

**Comment by matthewhanson** [comment] 2023-07-03 18:27
Hello @JonDHo, thanks for filing the issue.  

@piyushrpt is correct, the issue is that ESA is undergoing a massive reprocessing campaign and we're seeing a large numbers of failures on our side that I'm currently looking into

**Comment by matthewhanson** [comment] 2023-07-03 18:36
Also, @JonDHo , for any future problems use the new repo: https://github.com/Element84/earth-search/issues
The README has a a lot more info about the datasets and also has a mailing list you can sign up for with any major updates.

We'll send out an email later this week with an update, but I'll post here any updates in the meantime.

**Comment by JonDHo** [comment] 2023-07-03 19:49
Great, thanks.

**Comment by matthewhanson** [comment] 2023-07-04 18:13
@JonDHo Wanted to give you an update on this - the good news is that the missing files are on s3, they just aren't indexed.
So the conversion to COGs works, for the two L2A scenes you provided are:
s3://sentinel-cogs/sentinel-s2-l2a-cogs/19/H/BB/2023/6/S2A_19HBB_20230627_0_L2A/
s3://sentinel-cogs/sentinel-s2-l2a-cogs/18/H/YG/2023/6/S2A_18HYG_20230627_0_L2A/

But there is an issue with the subsequent indexing into the API that is failing. We're working to fix.

**Comment by JonDHo** [comment] 2023-07-05 19:40
ok. Gracias.

**Comment by JonDHo** [comment] 2023-07-10 15:25
Hi @matthewhanson, any update on the indexing?

**Comment by matthewhanson** [comment] 2023-07-10 21:24
@JonDHo I'm doing some final testing on our dev deployment today, stay tuned!

**Comment by matthewhanson** [comment] 2023-07-12 14:51
@JonDHo A fix was deployed yesterday and scenes that have failed ingest over the last several days are being rerun.
Let me know if you are still seeing missing scenes and I can look specifically at those.

**Comment by JonDHo** [comment] 2023-07-12 17:58
Not sure how long the indexing will take, but at the moment, this query is still returning no images:
[https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2023-06-27T00:00:00Z/2023-06-28T00:00:00Z&bbox=-72.5,-35,-72,-34.5](https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-l2a&datetime=2023-06-27T00:00:00Z/2023-06-28T00:00:00Z&bbox=-72.5,-35,-72,-34.5)

I am expecting it to return the following 4 scenes:
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HBB_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYG_20230627T224707
- S2A_MSIL1C_20230627T143731_N0509_R096_T19HBB_20230627T210535
- S2A_MSIL1C_20230627T143731_N0509_R096_T18HYG_20230627T210535

There are other images across Chile as well, but that is just one little focus area that I am using for testing.

**Comment by JonDHo** [comment] 2023-07-19 13:09
Seems that these are still missing. Any updates?
Thanks.

**Comment by matthewhanson** [comment] 2023-07-19 20:04
@JonDHo I ingested these scenes by manually kicking off the ingest - for some reason they never seemed to be queued up to begin with so I'm exploring why that might be.

**Comment by JonDHo** [comment] 2023-07-19 20:39
ok, thanks, as shown in the image in the comment above (https://github.com/cirrus-geo/cirrus-earth-search/issues/41#issuecomment-1618894643), there are lots of scenes on that particular day that were missing. I assume that there would be more beyond this specific area as well.

**Comment by JonDHo** [comment] 2023-07-21 13:31
@matthewhanson I understand if this is too much of a pain, but is there any chance of directly adding the following scenes to the index? This would greatly help us in helping provide access to this imagery to various levels of the Chilean government. This day in particular has a lot missing scenes and has fantastic coverage of the floods. I have checked them all and they all appear to be in the S3 bucket. 
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYH_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HXF_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYE_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HXE_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYJ_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T18HYF_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HBV_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HBC_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HCA_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HBD_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HCB_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HCC_20230627T224707
- S2A_MSIL2A_20230627T143731_N0509_R096_T19HCD_20230627T224707

**Comment by matthewhanson** [comment] 2023-07-25 03:50
@JonDHo Apologies for not solving this sooner - we've been rerunning failed scenes from the last several weeks but are also working migrating to a new improved workflow.  
In the meantime I've ingested the scenes you listed.

**Comment by gadomski** [comment] 2023-08-14 22:24
@JonDHo any chance you can check to see if the scenes you need are present? I'm working on closing out the issues on this repo, as https://github.com/Element84/earth-search/issues is the new location for issues with the Earth Search service. Thanks in advance!

**Comment by JonDHo** [comment] 2023-08-22 22:26
@gadomski yes, can do but will be next week after I get back from a bit of time off.

**Comment by JonDHo** [comment] 2023-09-01 18:51
Hi. I have had a chance to review whether the scenes are now available and it seems that they aren't. Using the Radiant Earth STAC Browser, I get the following for Chile on June 27 2023:

> ![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/6aaa89de-89ac-4225-850d-1106f738b83e)

This matches the coverage that I get when I query via the STAC API directly.

However, on SciHub, there is full coverage (note that this is only showing the first 150 results):

> ![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/5b329edd-66ae-4f8d-8687-fa1c389ff3ab)

And this is matched on Sentinel Hub:

> ![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/b8943875-9e7d-4748-a733-6e6a3cbe6256)

This is the max zoom possible whilst still seeing data on Sentinel Hub, so see the link below to browse properly - https://apps.sentinel-hub.com/eo-browser/?zoom=7&lat=-35.7168&lng=-70.75852&themeId=DEFAULT-THEME&visualizationUrl=https%3A%2F%2Fservices.sentinel-hub.com%2Fogc%2Fwms%2Fbd86bcc0-f318-402b-a145-015f85b9427e&datasetId=S2L2A&fromTime=2023-06-27T00%3A00%3A00.000Z&toTime=2023-06-27T23%3A59%3A59.999Z&layerId=1_TRUE_COLOR&demSource3D=%22MAPZEN%22

**Comment by JonDHo** [comment] 2023-09-01 18:55
I assume it is just a ridiculous coincidence that the temporal extent for the STAC catalog starts on the exact same day (June 27) 8 years earlier than this problem day??? 

![image](https://github.com/cirrus-geo/cirrus-earth-search/assets/3302774/63d45888-86dc-4aaa-8040-aa8ebea85e4d)

**Comment by gadomski** [comment] 2023-12-14 15:09
This issue should be fixed by the ongoing [Sentinel-2 reprocessing](https://us13.campaign-archive.com/?u=a7a7fcb1ce46c4d001fc76289&id=cf7934577f). That reprocessing should be complete after the first month of 2024 ... please re-open this issue if this issue persists after reprocessing.

**Closed by gadomski** 2023-12-14 15:09 UTC
